version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2

jobs:
  checkout:
    working_directory: ~/skillfuze
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-cache-v1-{{ checksum "yarn.lock" }}
            - dependencies-cache-v1-
      - run:
          name: Install Dependencies
          command: |
            yarn install --frozen-lockfile
            yarn bootstrap
      - save_cache:
          key: dependencies-cache-v1-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
            - ~/.cache/yarn
      - persist_to_workspace:
          root: ~/skillfuze
          paths:
            - ./*

  build:
    working_directory: ~/skillfuze
    docker:
      - image: circleci/node:lts
    steps:
      - attach_workspace:
          at: ~/skillfuze
      - run:
          name: Build Packages
          command: yarn build
      - persist_to_workspace:
          root: ~/skillfuze
          paths:
            - ./*

  lint:
    working_directory: ~/skillfuze
    docker:
      - image: circleci/node:lts
    steps:
      - attach_workspace:
          at: ~/skillfuze
      - run:
          name: Lint Packages
          command: yarn lint

  test:
    working_directory: ~/skillfuze
    docker:
      - image: circleci/node:lts
    steps:
      - attach_workspace:
          at: ~/skillfuze
      - run:
          name: Test Backend
          command: cd packages/backend && yarn test:cov -w 1 --ci --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: test-results
            JEST_JUNIT_OUTPUT_NAME: unit-results.xml
      - codecov/upload:
          file: packages/backend/coverage/clover.xml
      - store_test_results:
          path: packages/backend/test-results
      - store_artifacts:
          path: packages/backend/coverage

  test-e2e:
    working_directory: ~/skillfuze
    docker:
      - image: circleci/node:lts
      - image: circleci/mysql:8.0.12
        environment:
          MYSQL_ROOT_HOST: 127.0.0.1
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: skillfuze-test
    steps:
      - attach_workspace:
          at: ~/skillfuze
      - run:
          name: Install MySQL Client
          command: sudo apt-get install default-mysql-client
      - run:
          name: Prepare database
          command: |
            mysql -u root -p root \<<EOF
              ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'your_new_password';
              FLUSH PRIVILEGES;
              quit
            EOF
      - run:
          name: Test Backend E2E
          command: cd packages/backend && yarn test:e2e --ci --reporters=default --reporters=jest-junit --runInBand
          environment:
            JEST_JUNIT_OUTPUT_DIR: test-results
            JEST_JUNIT_OUTPUT_NAME: e2e-results.xml
      - store_test_results:
          path: packages/backend/test-results

  deploy:
    working_directory: ~/skillfuze
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - setup_remote_docker
      - add_ssh_keys:
          fingerprints:
            - 'fe:5b:b8:54:10:ed:67:d6:7e:23:a7:d4:45:0f:98:43'
      - run: ssh-keyscan $EC2_HOST >> ~/.ssh/known_hosts
      - run:
          name: Deploying Changes
          command: |
            set -e
            yarn deploy

workflows:
  build-and-test:
    jobs:
      - checkout
      - build:
          requires:
            - checkout
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
      - test-e2e:
          requires:
            - test
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
